baseURL: "http://darshansonde.com/"
languageCode: "en-us"
title: "Darshan Sonde"
theme: "hyde"
googleAnalytics: "UA-37371968-1"
disqusShortname: "darshansonde"
params:
  description: "Yet Another Geek Blog. Possibly abandoned ramblings for my future self"	